init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME.substring(1)"
      }
      else
      {
        Update-AppveyorBuild -Version "$(((nuget list RollingWindowExtremes -Source https://api.nuget.org/v3/index.json | findstr "RollingWindowExtremes[^.-]") -split ' ')[1])-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }
image: Visual Studio 2017
configuration: Release
environment:
  COVERALLS_REPO_TOKEN: b9992737-ee28-4d1f-9f83-8227478031b2
    secure: 
pull_requests:
  do_not_increment_build_number: true
before_build:
  - xcopy "C:\Program Files (x86)\MSBuild\Microsoft\Portable" "C:\Program Files\dotnet\sdk\2.1.200\Microsoft\Portable\" /S /E
  - dotnet restore -s https://api.nuget.org/v3/index.json
  - choco install opencover.portable
  - choco install codecov
  - nuget restore 
build_script:
  - cmd: dotnet pack -c Release RollingWindowExtremes
test_script:
  - OpenCover.Console.exe -register:user -target:dotnet.exe -targetargs:"test RollingWindowExtremes.Test\RollingWindowExtremes.Test.csproj" -filter:"+[RollingWindowExtremes]* -[RollingWindowExtremes.Test]*" -oldStyle
  - codecov -f results.xml
artifacts:
  - path: RollingWindowExtremes\bin\Release\RollingWindowExtremes.*
nuget:
  account_feed: true
deploy:
  - provider: NuGet
    on:
      appveyor_repo_tag: true
    api_key:
      secure: QB8FoYFBWfFy8cxyScelVPg3X4q2BvLO0VELkUAOKT4ZHp362V7cIRq+nIrkjFJ5
